-- =========================================================
-- AGROSMART - CREACIÓN COMPLETA DEL ESQUEMA DESDE CERO
-- Compatible con SQL*Plus / SQL Developer
-- =========================================================

-- CONECTAR COMO SYSTEM (O ADMIN DBA)
CONNECT system/12@localhost:1521/xepdb1;

PROMPT =========================================================
PROMPT ELIMINANDO USUARIOS EXISTENTES (AGROSMART, APP_USER)...
PROMPT =========================================================

-- Intentar eliminar si existen (ignorará errores si no existen)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER AGROSMART CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01918 THEN  -- usuario no existe
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER APP_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
  FOR s IN (
    SELECT synonym_name
    FROM all_synonyms
    WHERE owner = 'PUBLIC'
      AND synonym_name IN (
        'USUARIO', 'ADMINISTRADOR', 'EMPLEADO', 'CULTIVO', 'COSECHA',
        'INSUMO', 'TAREA', 'DETALLE_TAREA', 'ASIGNACION_TAREA',
        'LOG_NOTIFICACION_N8N',
        'SEQ_CULTIVO', 'SEQ_COSECHA', 'SEQ_INSUMO', 'SEQ_TAREA',
        'SEQ_DETALLE_TAREA', 'SEQ_ASIGNACION_TAREA', 'SEQ_LOG_NOTIFICACION_N8N'
      )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ' || s.synonym_name;
  END LOOP;
END;
/

PROMPT =========================================================
PROMPT CREANDO USUARIO PRINCIPAL (AGROSMART)...
PROMPT =========================================================

CREATE USER AGROSMART IDENTIFIED BY agro123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO AGROSMART;
ALTER USER AGROSMART DEFAULT ROLE ALL;
GRANT CREATE PUBLIC SYNONYM TO AGROSMART;

PROMPT =========================================================
PROMPT CREANDO USUARIO DE APLICACIÓN (APP_USER)...
PROMPT =========================================================

CREATE USER APP_USER IDENTIFIED BY app123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO APP_USER;
ALTER USER APP_USER DEFAULT ROLE ALL;

-- =========================================================
-- CONECTARSE COMO AGROSMART PARA CREAR LAS TABLAS
-- =========================================================
CONNECT AGROSMART/agro123@localhost:1521/xepdb1;

PROMPT =========================================================
PROMPT CREANDO TABLAS PRINCIPALES...
PROMPT =========================================================

CREATE TABLE USUARIO (
  ID_USUARIO       NUMBER            NOT NULL,
  PRIMER_NOMBRE    VARCHAR2(50)      NOT NULL,
  SEGUNDO_NOMBRE   VARCHAR2(50),
  PRIMER_APELLIDO  VARCHAR2(50)      NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(50),
  EMAIL            VARCHAR2(120)     NOT NULL,
  CONTRASENA       VARCHAR2(120)     NOT NULL,
  TELEFONO         NUMBER(15)        NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ADMINISTRADOR (
  ID_USUARIO     NUMBER        NOT NULL,
  MONTO_MENSUAL  NUMBER(12,2)  NOT NULL,
  CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (ID_USUARIO),
  CONSTRAINT FK_ADMIN_USUARIO FOREIGN KEY (ID_USUARIO)
      REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE EMPLEADO (
  ID_USUARIO        NUMBER        NOT NULL,
  MONTO_POR_HORA    NUMBER(12,2)  NOT NULL,
  MONTO_POR_JORNAL  NUMBER(12,2)  NOT NULL,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_USUARIO),
  CONSTRAINT FK_EMP_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CULTIVO (
  ID_CULTIVO              NUMBER        NOT NULL,
  ID_ADMIN_SUPERVISOR     NUMBER        NOT NULL,
  NOMBRE_LOTE             VARCHAR2(80)  NOT NULL,
  FECHA_SIEMBRA           DATE          NOT NULL,
  FECHA_COSECHA_ESTIMADA  DATE          NOT NULL,
  ALERTA_N8N              VARCHAR2(80)  DEFAULT 'SIN ALERTA',
  CONSTRAINT PK_CULTIVO PRIMARY KEY (ID_CULTIVO),
  CONSTRAINT FK_CULTIVO_ADMIN FOREIGN KEY (ID_ADMIN_SUPERVISOR)
      REFERENCES ADMINISTRADOR(ID_USUARIO)
);

CREATE TABLE COSECHA (
  ID_COSECHA          NUMBER         NOT NULL,
  ID_CULTIVO          NUMBER         NOT NULL,
  ID_ADMIN_REGISTRO   NUMBER         NOT NULL,
  FECHA_COSECHA       DATE           NOT NULL,
  FECHA_REGISTRO      DATE           NOT NULL,
  CANTIDAD_OBTENIDA   NUMBER(14,2)   NOT NULL,
  UNIDAD_MEDIDA       VARCHAR2(20)   NOT NULL,
  CALIDAD             VARCHAR2(30)   NOT NULL,
  OBSERVACIONES       VARCHAR2(200),
  CONSTRAINT PK_COSECHA PRIMARY KEY (ID_COSECHA),
  CONSTRAINT FK_COSECHA_CULTIVO FOREIGN KEY (ID_CULTIVO)
      REFERENCES CULTIVO(ID_CULTIVO),
  CONSTRAINT FK_COSECHA_ADMIN FOREIGN KEY (ID_ADMIN_REGISTRO)
      REFERENCES ADMINISTRADOR(ID_USUARIO)
);

CREATE TABLE INSUMO (
  ID_INSUMO          NUMBER         NOT NULL,
  ID_ADMIN_REGISTRO  NUMBER         NOT NULL,
  NOMBRE             VARCHAR2(120)  NOT NULL,
  TIPO               VARCHAR2(20)   NOT NULL,
  STOCK_ACTUAL       NUMBER(14,2)   NOT NULL,
  STOCK_MINIMO       NUMBER         NOT NULL,
  COSTO_UNITARIO     NUMBER(14,2)   NOT NULL,
  CONSTRAINT PK_INSUMO PRIMARY KEY (ID_INSUMO),
  CONSTRAINT FK_INSUMO_ADMIN FOREIGN KEY (ID_ADMIN_REGISTRO)
      REFERENCES ADMINISTRADOR(ID_USUARIO)
);

CREATE TABLE TAREA (
  ID_TAREA             NUMBER         NOT NULL,
  ID_CULTIVO           NUMBER         NOT NULL,
  ID_ADMIN_CREADOR     NUMBER         NOT NULL,
  TIPO_ACTIVIDAD       VARCHAR2(80)   NOT NULL,
  FECHA_PROGRAMADA     DATE           NOT NULL,
  TIEMPO_TOTAL_TAREA   NUMBER(8,2)    NOT NULL,
  ESTADO               VARCHAR2(20)   DEFAULT 'PENDIENTE' NOT NULL,
  ES_RECURRENTE        VARCHAR2(1)    DEFAULT 'F' NOT NULL,
  FRECUENCIA_DIAS      NUMBER(4),
  COSTO_TRANSPORTE     NUMBER(14,2),
  CONSTRAINT PK_TAREA PRIMARY KEY (ID_TAREA),
  CONSTRAINT FK_TAREA_CULTIVO FOREIGN KEY (ID_CULTIVO)
      REFERENCES CULTIVO(ID_CULTIVO),
  CONSTRAINT FK_TAREA_ADMIN FOREIGN KEY (ID_ADMIN_CREADOR)
      REFERENCES ADMINISTRADOR(ID_USUARIO)
);

CREATE TABLE DETALLE_TAREA (
  ID_DETALLE_TAREA   NUMBER        NOT NULL,
  ID_TAREA           NUMBER        NOT NULL,
  ID_INSUMO          NUMBER        NOT NULL,
  CANTIDAD_USADA     NUMBER(14,2)  NOT NULL,
  CONSTRAINT PK_DETALLE_TAREA PRIMARY KEY (ID_DETALLE_TAREA),
  CONSTRAINT FK_DETALLE_TAREA_TAREA FOREIGN KEY (ID_TAREA)
      REFERENCES TAREA(ID_TAREA),
  CONSTRAINT FK_DETALLE_TAREA_INSUMO FOREIGN KEY (ID_INSUMO)
      REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE ASIGNACION_TAREA (
  ID_ASIG_TAREA        NUMBER        NOT NULL,
  ID_TAREA             NUMBER        NOT NULL,
  ID_EMPLEADO          NUMBER        NOT NULL,
  ID_ADMIN_ASIGNADOR   NUMBER        NOT NULL,
  FECHA_ASIGNACION     DATE          NOT NULL,
  HORAS_TRABAJADAS     NUMBER(7,2),
  JORNADAS_TRABAJADAS  NUMBER(7,2),
  PAGO_ACORDADO        NUMBER(12,2),
  ESTADO               VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
  CONSTRAINT PK_ASIGNACION_TAREA PRIMARY KEY (ID_ASIG_TAREA),
  CONSTRAINT FK_ASIG_TAREA_TAREA FOREIGN KEY (ID_TAREA)
      REFERENCES TAREA(ID_TAREA),
  CONSTRAINT FK_ASIG_TAREA_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO(ID_USUARIO),
  CONSTRAINT FK_ASIG_TAREA_ADMIN FOREIGN KEY (ID_ADMIN_ASIGNADOR)
      REFERENCES ADMINISTRADOR(ID_USUARIO)
);

CREATE TABLE LOG_NOTIFICACION_N8N (
  ID_LOG         NUMBER          NOT NULL,
  TIPO           VARCHAR2(30)    NOT NULL,
  REFERENCIA_ID  NUMBER          NOT NULL,
  MENSAJE        VARCHAR2(4000)  NOT NULL,
  DESTINATARIO   VARCHAR2(320)   NOT NULL,
  FECHA_ENVIO    DATE            DEFAULT SYSDATE NOT NULL,
  FECHA_ENVIO_DIA GENERATED ALWAYS AS (TRUNC(FECHA_ENVIO)) VIRTUAL,
  CONSTRAINT PK_LOG_NOTIFICACION_N8N PRIMARY KEY (ID_LOG)
);

-- =========================================================
-- SECUENCIAS Y TRIGGERS
-- =========================================================
PROMPT CREANDO SECUENCIAS Y TRIGGERS...

CREATE SEQUENCE SEQ_CULTIVO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_CULTIVO
BEFORE INSERT ON CULTIVO
FOR EACH ROW
WHEN (NEW.ID_CULTIVO IS NULL)
BEGIN
  :NEW.ID_CULTIVO := SEQ_CULTIVO.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_COSECHA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_COSECHA
BEFORE INSERT ON COSECHA
FOR EACH ROW
WHEN (NEW.ID_COSECHA IS NULL)
BEGIN
  :NEW.ID_COSECHA := SEQ_COSECHA.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_INSUMO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_INSUMO
BEFORE INSERT ON INSUMO
FOR EACH ROW
WHEN (NEW.ID_INSUMO IS NULL)
BEGIN
  :NEW.ID_INSUMO := SEQ_INSUMO.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_TAREA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_TAREA
BEFORE INSERT ON TAREA
FOR EACH ROW
WHEN (NEW.ID_TAREA IS NULL)
BEGIN
  :NEW.ID_TAREA := SEQ_TAREA.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_DETALLE_TAREA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_DETALLE_TAREA
BEFORE INSERT ON DETALLE_TAREA
FOR EACH ROW
WHEN (NEW.ID_DETALLE_TAREA IS NULL)
BEGIN
  :NEW.ID_DETALLE_TAREA := SEQ_DETALLE_TAREA.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_ASIGNACION_TAREA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_ASIGNACION_TAREA
BEFORE INSERT ON ASIGNACION_TAREA
FOR EACH ROW
WHEN (NEW.ID_ASIG_TAREA IS NULL)
BEGIN
  :NEW.ID_ASIG_TAREA := SEQ_ASIGNACION_TAREA.NEXTVAL;
END;
/

CREATE SEQUENCE SEQ_LOG_NOTIFICACION_N8N START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_LOG_NOTIFICACION_N8N
BEFORE INSERT ON LOG_NOTIFICACION_N8N
FOR EACH ROW
WHEN (NEW.ID_LOG IS NULL)
BEGIN
  :NEW.ID_LOG := SEQ_LOG_NOTIFICACION_N8N.NEXTVAL;
END;
/

-- =========================================================
-- SINÓNIMOS PÚBLICOS
-- =========================================================
CONNECT system/camilogamer@localhost:1521/xepdb1;

PROMPT CREANDO SINÓNIMOS PÚBLICOS...

CREATE PUBLIC SYNONYM USUARIO              FOR AGROSMART.USUARIO;
CREATE PUBLIC SYNONYM ADMINISTRADOR        FOR AGROSMART.ADMINISTRADOR;
CREATE PUBLIC SYNONYM EMPLEADO             FOR AGROSMART.EMPLEADO;
CREATE PUBLIC SYNONYM CULTIVO              FOR AGROSMART.CULTIVO;
CREATE PUBLIC SYNONYM COSECHA              FOR AGROSMART.COSECHA;
CREATE PUBLIC SYNONYM INSUMO               FOR AGROSMART.INSUMO;
CREATE PUBLIC SYNONYM TAREA                FOR AGROSMART.TAREA;
CREATE PUBLIC SYNONYM DETALLE_TAREA        FOR AGROSMART.DETALLE_TAREA;
CREATE PUBLIC SYNONYM ASIGNACION_TAREA     FOR AGROSMART.ASIGNACION_TAREA;
CREATE PUBLIC SYNONYM LOG_NOTIFICACION_N8N FOR AGROSMART.LOG_NOTIFICACION_N8N;

CREATE PUBLIC SYNONYM SEQ_CULTIVO              FOR AGROSMART.SEQ_CULTIVO;
CREATE PUBLIC SYNONYM SEQ_COSECHA              FOR AGROSMART.SEQ_COSECHA;
CREATE PUBLIC SYNONYM SEQ_INSUMO               FOR AGROSMART.SEQ_INSUMO;
CREATE PUBLIC SYNONYM SEQ_TAREA                FOR AGROSMART.SEQ_TAREA;
CREATE PUBLIC SYNONYM SEQ_DETALLE_TAREA        FOR AGROSMART.SEQ_DETALLE_TAREA;
CREATE PUBLIC SYNONYM SEQ_ASIGNACION_TAREA     FOR AGROSMART.SEQ_ASIGNACION_TAREA;
CREATE PUBLIC SYNONYM SEQ_LOG_NOTIFICACION_N8N FOR AGROSMART.SEQ_LOG_NOTIFICACION_N8N;

-- =========================================================
-- PERMISOS AL USUARIO APP_USER
-- =========================================================
PROMPT ASIGNANDO PERMISOS A APP_USER...

GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.USUARIO              TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.ADMINISTRADOR        TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.EMPLEADO             TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.CULTIVO              TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.COSECHA              TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.INSUMO               TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.TAREA                TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.DETALLE_TAREA        TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.ASIGNACION_TAREA     TO APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGROSMART.LOG_NOTIFICACION_N8N TO APP_USER;

PROMPT =========================================================
PROMPT ✅ SCRIPT COMPLETADO CON ÉXITO ✅
PROMPT =========================================================
EXIT;

